name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day automatically
  workflow_dispatch:        # lets you run it manually too

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
